### ISSUE TITLE
Comments are removed during conversion

### ISSUE THREAD

**Issue by dcalhoun** [buxlabs/amd-to-es6#18] opened 2017-03-03 17:37 UTC
It would appear both inline and block comments are completely removed during the conversion. The following...

```javascript 
define([
  'underscore',
  // Move this
  'marionette'
], (_, Marionette) =>
  // This is a view
  Marionette.ItemView.extend({
    getTemplate () {
      /**
       * We are doing work here
       */
      return ''
    }
  })
)
```

Results in...
```javascript
import _ from 'underscore';
import Marionette from 'marionette';
export default Marionette.ItemView.extend({
    getTemplate() {
        return '';
    }
});
```

Is there a way to preserve comments?

**Comment by emilos** [comment] 2017-03-03 17:42
@dcalhoun yes, but only a really basic one that might not fit your purpose. The converter accepts a `comments` option https://github.com/buxlabs/ast/blob/master/index.js#L89

Preserving comments is quite tricky, e.g. because you change the code in a destructive way while converting, I played with this a little and in my use case it was acceptable to omit (not a big fan of comments). PRs are highly welcome for this one in the `@buxlabs/ast` dependency.

**Comment by dcalhoun** [comment] 2017-03-03 17:48
Ah, ok. Sorry that I missed that note in the README. Thank you for the information.

**Comment by emilos** [comment] 2017-06-16 07:37
@dcalhoun I've investigated this issue a little bit more and now I've switched from acorn to espree to make the comments support a little bit better - for now it leaves them in places where code did not do any destructive manipulations. It's not perfect, but much better than what we had before.

https://github.com/buxlabs/ast/commit/81e6ef0550fd2a76829af81433c02b181e805e6d
https://github.com/buxlabs/amd-to-es6/commit/a57fba464c3eacb523f80caf04728ef5d04e9619

edit: this has been released as `v0.9.0`

**Closed as completed by emilos** 2017-06-16 07:37 UTC
Labels: enhancement

**Comment by dcalhoun** [comment] 2017-06-16 11:27
Great. Thank you. 

David Calhoun
Software Engineer
DavidCalhoun.me

**Comment by orlov-vo** [comment] 2019-06-12 08:22
It has regression bug now on latest version `0.13.3`. You removed this support of comments in `0.13.0` - why? Have you any plan to return it back?

input:
```js
"use strict";
define( function( require ) {

    var Widget = require( "common/widget" ),
        Edit = require( "./index" );

    return Widget( Edit, {

        /** @type {boolean} Flag for company section */
        _isCompanySection: false,

        /**
         * Handler for loading
         * @private
         */
        onLoad: function() {
            this.documents.load(); // TODO: Okay?
        }
    } );
} );
```

output:
```js
import Widget from "common/widget";
import Edit from "./index";
export default Widget(Edit, {
  _isCompanySection: false,
  onLoad: function () {
    this.documents.load();
  }
});
```
